Creating Login Page
CS196Illinois/Group-12-SP21 pull request #14
Opened 2021-03-26 12:46 UTC by jchoi25

2021-03-28 13:58 UTC, jchoi25 commented
I have created a sample login page. It currently does not login or remembers the user.

2021-03-28 21:11 UTC, amit-sawhney requested changes

2021-03-28 21:11 UTC, amit-sawhney commented on login/src/App.js
> +const App = () => {
Could you add screenshots to the PR?

2021-03-29 00:09 UTC, jchoi25 commented on login/src/App.js
> +const App = () => {
I'll do that right now

2021-03-29 00:14 UTC, jchoi25 commented
I have moved everything into Project. Here is a screenshot of what the login page currently looks like. The Sign In button submits what is typed in the textboxes but does not actually do anything. Remember Me does not do anything as well. Both the username and password are required fields.
![screenshot](https://user-images.githubusercontent.com/79821480/112773011-231ffa80-906f-11eb-98ea-2b8d2c947b6a.jpg)

2021-03-31 20:22 UTC, amit-sawhney requested changes
Please remember my instructions. The React app already exists. Right now, you have an entire app called "login" within the project page. You will need to delete this entire app AFTER copying and pasting the code from each file over. 

Let me reiterate:

You will need to copy your code changes, file by file (this will likely only be the App.js file and App.css that is any different). 

Also, can you see if you can center the entire think vertically.

Look into display: flex and align-items: center.

Further note: 

- We won't be having a password or remember me. We don't have a database. Right now, we will just accept a spotify user name and try to pull the data for that Spotify user through the api if possible

2021-04-01 13:30 UTC, jchoi25 commented
I have removed remember me and the password input. Everything is now aligned in the center.
![screenshot](https://user-images.githubusercontent.com/79821480/113301325-e20f3b00-9339-11eb-8cf0-8748d86fab62.jpg)

2021-04-11 21:17 UTC, amit-sawhney submitted a review, later dismissed

2021-04-18 21:23 UTC, amit-sawhney approved these changes

2021-04-21 00:35 UTC, merged